language: node_js
node_js: "stable"
env:
  global:
  - secure: Yars/3dL27/QUmFhpRAZKoAe5wps6/S1jsNtpdJzdUrdaATzjSPtNqykl7o/hrxXx3ugZbHU/x93CIraXADRvtGc3lSN2crkKXv0hNrzn9s2u6cMXwqiT+JblyYy5bdIBqoLU4UoXnaxbPr9HUPIXpHTezH8O9mZQjJdliuXqdi3iHnn4PXODh1hQ/Nync7adcCqfu1nbowNe7AkfLe39R8FMNDz1pdo+EwXWiwvYAbOBru0WgVVpi+v/ReYlIRL821DhQVTVELe5L3QFXDz84Jo31je3KlRne5mldKdL77i9To0riks/kZpBbCC72D8KjPxXOPSbA+8SMod6GSA0BJtGwLNalhuqG6bhqlBMOK2NT7FzM/FLvdEeW9LPOCevGRwc2FPJ81XjJ+G18eDuaSA3Y2+oTsCg3V7rISjiRRCBDlfHANKhs52JliF3AQhwWdo5CAEZmeBjlSvZeBc2hi97Hx/Z9ATsp4IvTtbVXNP8dnWIHyRvFIV5g5+le8KQ6sl4c98gG6HcuGnpj6oL9uG3EKVGY8fNmttC9bpDZKCi9DBC4YOd3uuwdAydRm185vRnlPP8k63i/5SKiJTchLgsC6O9iC2bROR99RnsYEV3X6EjgG8eXBHXTuabtaUYcLvizPNwGlJlem2d1BrktdE69owMiD6typoJfQY4TM=
  - secure: vIRKRG6/TJSkxWFIeMake73ae/tUiSyUBGIBcA+Jwsb3Dn9jneMJUlnmUbG5L2oj5u0nrf2KWCIKxhAwKCOAPIpLwFTmcps1J7I4ikoiuSXhxxAqCeKZp2hu1QJ6XF9gfiY+SbJwdu4AIh1VhGVAzLb9LaT6mXAoOf5tGXIcKUDQjlcL3aYCV5Uinkfcy2yMUVOOxxMY8AF288swlZJNs3QNEq79OW7a9q8AB0IjCx29l+/F4E5cw6dtlVplFyX1hOfac0ZIttlKtGP9cGrRX/PUfC5xTTUAKksx5s2p2sUH4z5l+3gmFAwE10/8RIlVNH1132jOhPma0yD8N4L92Pmt+xF+3RjquojvlR/NpPUauy3YP0hhqvkBjJjUcbDRtrhH7jEkfMjYsjcgNDYYpdC+RljRPrijummrwEQzz5p1bmucQNVkxfgKwxRwfXy2uGbgWf+ydafjeRMvfFxuvG+otxA+ADCCjS4SVS68UC8VUxDPDebMIZiXgyG8Mf8C65TvTe632WtByegjTEdBwz3dfB6f20s4oxsl2WrUFKZ1KcAyAzgsNZmSVBmCC7cnW6+arv9VESBUsWiRfyRwSNcrYmASjR58NPMNE82PHRR7uPJwTwCaUrBLnFJMNGDbgMeUc5lPfyG6qS2oP08s9Ema6q+IyVvLrXywrokLV4c=
  - COMMIT=${TRAVIS_COMMIT::8}
before_install:
    - npm install -g @angular/cli

sudo: required

services:
    - docker
script:
   - ng build --prod
  
after_success:
    - if  [ $TRAVIS_PULL_REQUEST = "false" ]; then
        export REPO=avneetsingh/openebs-website;
        docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -f Dockerfile -t $REPO:$COMMIT . && docker push $REPO;
      fi  

notifications:
  email:
    on_success: never
on_failure: always

